//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientePrueba.MaterialAceroGH {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AceroGHerramienta", Namespace="http://schemas.datacontract.org/2004/07/WSMateriales.Entidades")]
    [System.SerializableAttribute()]
    public partial class AceroGHerramienta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcabadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MedidasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_aceroghField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Acabado {
            get {
                return this.AcabadoField;
            }
            set {
                if ((object.ReferenceEquals(this.AcabadoField, value) != true)) {
                    this.AcabadoField = value;
                    this.RaisePropertyChanged("Acabado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calidad {
            get {
                return this.CalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.CalidadField, value) != true)) {
                    this.CalidadField = value;
                    this.RaisePropertyChanged("Calidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Medidas {
            get {
                return this.MedidasField;
            }
            set {
                if ((object.ReferenceEquals(this.MedidasField, value) != true)) {
                    this.MedidasField = value;
                    this.RaisePropertyChanged("Medidas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Perfil {
            get {
                return this.PerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfilField, value) != true)) {
                    this.PerfilField = value;
                    this.RaisePropertyChanged("Perfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_acerogh {
            get {
                return this.id_aceroghField;
            }
            set {
                if ((this.id_aceroghField.Equals(value) != true)) {
                    this.id_aceroghField = value;
                    this.RaisePropertyChanged("id_acerogh");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaterialAceroGH.IMaterialAceroGH")]
    public interface IMaterialAceroGH {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroGH/BuscarTodos", ReplyAction="http://tempuri.org/IMaterialAceroGH/BuscarTodosResponse")]
        ClientePrueba.MaterialAceroGH.AceroGHerramienta[] BuscarTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroGH/BuscarTodos", ReplyAction="http://tempuri.org/IMaterialAceroGH/BuscarTodosResponse")]
        System.Threading.Tasks.Task<ClientePrueba.MaterialAceroGH.AceroGHerramienta[]> BuscarTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroGH/BucarId", ReplyAction="http://tempuri.org/IMaterialAceroGH/BucarIdResponse")]
        ClientePrueba.MaterialAceroGH.AceroGHerramienta BucarId(string id_acerogh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroGH/BucarId", ReplyAction="http://tempuri.org/IMaterialAceroGH/BucarIdResponse")]
        System.Threading.Tasks.Task<ClientePrueba.MaterialAceroGH.AceroGHerramienta> BucarIdAsync(string id_acerogh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroGH/Create", ReplyAction="http://tempuri.org/IMaterialAceroGH/CreateResponse")]
        bool Create(ClientePrueba.MaterialAceroGH.AceroGHerramienta acerogh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroGH/Create", ReplyAction="http://tempuri.org/IMaterialAceroGH/CreateResponse")]
        System.Threading.Tasks.Task<bool> CreateAsync(ClientePrueba.MaterialAceroGH.AceroGHerramienta acerogh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroGH/Edit", ReplyAction="http://tempuri.org/IMaterialAceroGH/EditResponse")]
        void Edit(ClientePrueba.MaterialAceroGH.AceroGHerramienta acerogh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroGH/Edit", ReplyAction="http://tempuri.org/IMaterialAceroGH/EditResponse")]
        System.Threading.Tasks.Task EditAsync(ClientePrueba.MaterialAceroGH.AceroGHerramienta acerogh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroGH/Delete", ReplyAction="http://tempuri.org/IMaterialAceroGH/DeleteResponse")]
        bool Delete(ClientePrueba.MaterialAceroGH.AceroGHerramienta acerogh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroGH/Delete", ReplyAction="http://tempuri.org/IMaterialAceroGH/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(ClientePrueba.MaterialAceroGH.AceroGHerramienta acerogh);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMaterialAceroGHChannel : ClientePrueba.MaterialAceroGH.IMaterialAceroGH, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaterialAceroGHClient : System.ServiceModel.ClientBase<ClientePrueba.MaterialAceroGH.IMaterialAceroGH>, ClientePrueba.MaterialAceroGH.IMaterialAceroGH {
        
        public MaterialAceroGHClient() {
        }
        
        public MaterialAceroGHClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaterialAceroGHClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialAceroGHClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialAceroGHClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientePrueba.MaterialAceroGH.AceroGHerramienta[] BuscarTodos() {
            return base.Channel.BuscarTodos();
        }
        
        public System.Threading.Tasks.Task<ClientePrueba.MaterialAceroGH.AceroGHerramienta[]> BuscarTodosAsync() {
            return base.Channel.BuscarTodosAsync();
        }
        
        public ClientePrueba.MaterialAceroGH.AceroGHerramienta BucarId(string id_acerogh) {
            return base.Channel.BucarId(id_acerogh);
        }
        
        public System.Threading.Tasks.Task<ClientePrueba.MaterialAceroGH.AceroGHerramienta> BucarIdAsync(string id_acerogh) {
            return base.Channel.BucarIdAsync(id_acerogh);
        }
        
        public bool Create(ClientePrueba.MaterialAceroGH.AceroGHerramienta acerogh) {
            return base.Channel.Create(acerogh);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAsync(ClientePrueba.MaterialAceroGH.AceroGHerramienta acerogh) {
            return base.Channel.CreateAsync(acerogh);
        }
        
        public void Edit(ClientePrueba.MaterialAceroGH.AceroGHerramienta acerogh) {
            base.Channel.Edit(acerogh);
        }
        
        public System.Threading.Tasks.Task EditAsync(ClientePrueba.MaterialAceroGH.AceroGHerramienta acerogh) {
            return base.Channel.EditAsync(acerogh);
        }
        
        public bool Delete(ClientePrueba.MaterialAceroGH.AceroGHerramienta acerogh) {
            return base.Channel.Delete(acerogh);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(ClientePrueba.MaterialAceroGH.AceroGHerramienta acerogh) {
            return base.Channel.DeleteAsync(acerogh);
        }
    }
}
