//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSMateriales.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialMateriales
    {
        public int id_Material { get; set; }
        public int EntradaMaterial { get; set; }
        public Nullable<int> SalidaMaterial { get; set; }
        public Nullable<System.DateTime> FechaEntrada { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
    }
}
