//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientePrueba.MaterialAceroInoxidable {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AceroInoxidable", Namespace="http://schemas.datacontract.org/2004/07/WSMateriales.Entidades")]
    [System.SerializableAttribute()]
    public partial class AceroInoxidable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcabadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EspesorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_aceroInoxField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Acabado {
            get {
                return this.AcabadoField;
            }
            set {
                if ((object.ReferenceEquals(this.AcabadoField, value) != true)) {
                    this.AcabadoField = value;
                    this.RaisePropertyChanged("Acabado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calidad {
            get {
                return this.CalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.CalidadField, value) != true)) {
                    this.CalidadField = value;
                    this.RaisePropertyChanged("Calidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Espesor {
            get {
                return this.EspesorField;
            }
            set {
                if ((object.ReferenceEquals(this.EspesorField, value) != true)) {
                    this.EspesorField = value;
                    this.RaisePropertyChanged("Espesor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Perfil {
            get {
                return this.PerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfilField, value) != true)) {
                    this.PerfilField = value;
                    this.RaisePropertyChanged("Perfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_aceroInox {
            get {
                return this.id_aceroInoxField;
            }
            set {
                if ((this.id_aceroInoxField.Equals(value) != true)) {
                    this.id_aceroInoxField = value;
                    this.RaisePropertyChanged("id_aceroInox");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaterialAceroInoxidable.IMaterialAceroInoxi")]
    public interface IMaterialAceroInoxi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroInoxi/BuscarTodos", ReplyAction="http://tempuri.org/IMaterialAceroInoxi/BuscarTodosResponse")]
        ClientePrueba.MaterialAceroInoxidable.AceroInoxidable[] BuscarTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroInoxi/BuscarTodos", ReplyAction="http://tempuri.org/IMaterialAceroInoxi/BuscarTodosResponse")]
        System.Threading.Tasks.Task<ClientePrueba.MaterialAceroInoxidable.AceroInoxidable[]> BuscarTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroInoxi/BucarId", ReplyAction="http://tempuri.org/IMaterialAceroInoxi/BucarIdResponse")]
        ClientePrueba.MaterialAceroInoxidable.AceroInoxidable BucarId(string id_aceroInox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroInoxi/BucarId", ReplyAction="http://tempuri.org/IMaterialAceroInoxi/BucarIdResponse")]
        System.Threading.Tasks.Task<ClientePrueba.MaterialAceroInoxidable.AceroInoxidable> BucarIdAsync(string id_aceroInox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroInoxi/Create", ReplyAction="http://tempuri.org/IMaterialAceroInoxi/CreateResponse")]
        bool Create(ClientePrueba.MaterialAceroInoxidable.AceroInoxidable aceroinox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroInoxi/Create", ReplyAction="http://tempuri.org/IMaterialAceroInoxi/CreateResponse")]
        System.Threading.Tasks.Task<bool> CreateAsync(ClientePrueba.MaterialAceroInoxidable.AceroInoxidable aceroinox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroInoxi/Edit", ReplyAction="http://tempuri.org/IMaterialAceroInoxi/EditResponse")]
        void Edit(ClientePrueba.MaterialAceroInoxidable.AceroInoxidable aceroinox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroInoxi/Edit", ReplyAction="http://tempuri.org/IMaterialAceroInoxi/EditResponse")]
        System.Threading.Tasks.Task EditAsync(ClientePrueba.MaterialAceroInoxidable.AceroInoxidable aceroinox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroInoxi/Delete", ReplyAction="http://tempuri.org/IMaterialAceroInoxi/DeleteResponse")]
        bool Delete(ClientePrueba.MaterialAceroInoxidable.AceroInoxidable aceroinox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialAceroInoxi/Delete", ReplyAction="http://tempuri.org/IMaterialAceroInoxi/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(ClientePrueba.MaterialAceroInoxidable.AceroInoxidable aceroinox);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMaterialAceroInoxiChannel : ClientePrueba.MaterialAceroInoxidable.IMaterialAceroInoxi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaterialAceroInoxiClient : System.ServiceModel.ClientBase<ClientePrueba.MaterialAceroInoxidable.IMaterialAceroInoxi>, ClientePrueba.MaterialAceroInoxidable.IMaterialAceroInoxi {
        
        public MaterialAceroInoxiClient() {
        }
        
        public MaterialAceroInoxiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaterialAceroInoxiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialAceroInoxiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialAceroInoxiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientePrueba.MaterialAceroInoxidable.AceroInoxidable[] BuscarTodos() {
            return base.Channel.BuscarTodos();
        }
        
        public System.Threading.Tasks.Task<ClientePrueba.MaterialAceroInoxidable.AceroInoxidable[]> BuscarTodosAsync() {
            return base.Channel.BuscarTodosAsync();
        }
        
        public ClientePrueba.MaterialAceroInoxidable.AceroInoxidable BucarId(string id_aceroInox) {
            return base.Channel.BucarId(id_aceroInox);
        }
        
        public System.Threading.Tasks.Task<ClientePrueba.MaterialAceroInoxidable.AceroInoxidable> BucarIdAsync(string id_aceroInox) {
            return base.Channel.BucarIdAsync(id_aceroInox);
        }
        
        public bool Create(ClientePrueba.MaterialAceroInoxidable.AceroInoxidable aceroinox) {
            return base.Channel.Create(aceroinox);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAsync(ClientePrueba.MaterialAceroInoxidable.AceroInoxidable aceroinox) {
            return base.Channel.CreateAsync(aceroinox);
        }
        
        public void Edit(ClientePrueba.MaterialAceroInoxidable.AceroInoxidable aceroinox) {
            base.Channel.Edit(aceroinox);
        }
        
        public System.Threading.Tasks.Task EditAsync(ClientePrueba.MaterialAceroInoxidable.AceroInoxidable aceroinox) {
            return base.Channel.EditAsync(aceroinox);
        }
        
        public bool Delete(ClientePrueba.MaterialAceroInoxidable.AceroInoxidable aceroinox) {
            return base.Channel.Delete(aceroinox);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(ClientePrueba.MaterialAceroInoxidable.AceroInoxidable aceroinox) {
            return base.Channel.DeleteAsync(aceroinox);
        }
    }
}
