//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientePrueba.CUsuarios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WSMateriales.Entidades")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CUsuarios.IAddUser")]
    public interface IAddUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddUser/NewUser", ReplyAction="http://tempuri.org/IAddUser/NewUserResponse")]
        bool NewUser(ClientePrueba.CUsuarios.Usuario user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddUser/NewUser", ReplyAction="http://tempuri.org/IAddUser/NewUserResponse")]
        System.Threading.Tasks.Task<bool> NewUserAsync(ClientePrueba.CUsuarios.Usuario user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddUser/DeleteUser", ReplyAction="http://tempuri.org/IAddUser/DeleteUserResponse")]
        bool DeleteUser(ClientePrueba.CUsuarios.Usuario user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddUser/DeleteUser", ReplyAction="http://tempuri.org/IAddUser/DeleteUserResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserAsync(ClientePrueba.CUsuarios.Usuario user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddUser/EditUser", ReplyAction="http://tempuri.org/IAddUser/EditUserResponse")]
        void EditUser(ClientePrueba.CUsuarios.Usuario user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddUser/EditUser", ReplyAction="http://tempuri.org/IAddUser/EditUserResponse")]
        System.Threading.Tasks.Task EditUserAsync(ClientePrueba.CUsuarios.Usuario user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddUser/ConsultarTodos", ReplyAction="http://tempuri.org/IAddUser/ConsultarTodosResponse")]
        ClientePrueba.CUsuarios.Usuario[] ConsultarTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddUser/ConsultarTodos", ReplyAction="http://tempuri.org/IAddUser/ConsultarTodosResponse")]
        System.Threading.Tasks.Task<ClientePrueba.CUsuarios.Usuario[]> ConsultarTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddUser/ConsultarPorMail", ReplyAction="http://tempuri.org/IAddUser/ConsultarPorMailResponse")]
        ClientePrueba.CUsuarios.Usuario[] ConsultarPorMail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddUser/ConsultarPorMail", ReplyAction="http://tempuri.org/IAddUser/ConsultarPorMailResponse")]
        System.Threading.Tasks.Task<ClientePrueba.CUsuarios.Usuario[]> ConsultarPorMailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddUser/ConsultarPorId", ReplyAction="http://tempuri.org/IAddUser/ConsultarPorIdResponse")]
        ClientePrueba.CUsuarios.Usuario ConsultarPorId(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddUser/ConsultarPorId", ReplyAction="http://tempuri.org/IAddUser/ConsultarPorIdResponse")]
        System.Threading.Tasks.Task<ClientePrueba.CUsuarios.Usuario> ConsultarPorIdAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddUserChannel : ClientePrueba.CUsuarios.IAddUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddUserClient : System.ServiceModel.ClientBase<ClientePrueba.CUsuarios.IAddUser>, ClientePrueba.CUsuarios.IAddUser {
        
        public AddUserClient() {
        }
        
        public AddUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool NewUser(ClientePrueba.CUsuarios.Usuario user) {
            return base.Channel.NewUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> NewUserAsync(ClientePrueba.CUsuarios.Usuario user) {
            return base.Channel.NewUserAsync(user);
        }
        
        public bool DeleteUser(ClientePrueba.CUsuarios.Usuario user) {
            return base.Channel.DeleteUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserAsync(ClientePrueba.CUsuarios.Usuario user) {
            return base.Channel.DeleteUserAsync(user);
        }
        
        public void EditUser(ClientePrueba.CUsuarios.Usuario user) {
            base.Channel.EditUser(user);
        }
        
        public System.Threading.Tasks.Task EditUserAsync(ClientePrueba.CUsuarios.Usuario user) {
            return base.Channel.EditUserAsync(user);
        }
        
        public ClientePrueba.CUsuarios.Usuario[] ConsultarTodos() {
            return base.Channel.ConsultarTodos();
        }
        
        public System.Threading.Tasks.Task<ClientePrueba.CUsuarios.Usuario[]> ConsultarTodosAsync() {
            return base.Channel.ConsultarTodosAsync();
        }
        
        public ClientePrueba.CUsuarios.Usuario[] ConsultarPorMail(string email) {
            return base.Channel.ConsultarPorMail(email);
        }
        
        public System.Threading.Tasks.Task<ClientePrueba.CUsuarios.Usuario[]> ConsultarPorMailAsync(string email) {
            return base.Channel.ConsultarPorMailAsync(email);
        }
        
        public ClientePrueba.CUsuarios.Usuario ConsultarPorId(string id) {
            return base.Channel.ConsultarPorId(id);
        }
        
        public System.Threading.Tasks.Task<ClientePrueba.CUsuarios.Usuario> ConsultarPorIdAsync(string id) {
            return base.Channel.ConsultarPorIdAsync(id);
        }
    }
}
